services:
  db:
    image: postgres:16
    container_name: raw_telemetry_pg
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata_raw:/var/lib/postgresql/data
  adminer:
    image: adminer:4
    container_name: raw_telemetry_adminer
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata_raw:
